# Generated by Django 5.1.7 on 2025-03-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_teacher_salary_alter_salary_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_record', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.user'),
        ),
    ]
